toi-3.13: mm: fix shmem functions calls
This commit tries to fix shmem_file_setup() calls due to API
changes in 3.13 kernel:

===
 struct file *shmem_kernel_file_setup(const char *name, loff_t size, unsigned long flags, atomic_copy)
                                                                                          ^
mm/shmem.c:3001:83: error: unknown type name ‘atomic_copy’
 struct file *shmem_file_setup(const char *name, loff_t size, unsigned long flags, atomic_copy)
                                                                                   ^
mm/shmem.c: In function ‘shmem_zero_setup’:
mm/shmem.c:3016:2: error: too many arguments to function ‘shmem_file_setup’
  file = shmem_file_setup("dev/zero", size, vma->vm_flags, 0, 0);
  ^
In file included from include/linux/linkage.h:6:0,
                 from include/linux/fs.h:5,
                 from mm/shmem.c:24:
mm/shmem.c:3005:19: note: declared here
 EXPORT_SYMBOL_GPL(shmem_file_setup);
                   ^
include/linux/export.h:57:21: note: in definition of macro ‘__EXPORT_SYMBOL’
  extern typeof(sym) sym;     \
                     ^
mm/shmem.c:3005:1: note: in expansion of macro ‘EXPORT_SYMBOL_GPL’
 EXPORT_SYMBOL_GPL(shmem_file_setup);
 ^
mm/shmem.c: At top level:
mm/shmem.c:2923:21: warning: ‘__shmem_file_setup’ defined but not used [-Wunused-function]
 static struct file *__shmem_file_setup(const char *name, loff_t size,
                     ^
  AS      arch/x86/kernel/vsyscall_emu_64.o
  AS [M]  arch/x86/crypto/twofish-x86_64-asm_64.o
scripts/Makefile.build:308: recipe for target 'mm/shmem.o' failed
make[1]: *** [mm/shmem.o] Error 1
Makefile:816: recipe for target 'mm' failed
make: *** [mm] Error 2
make: *** Waiting for unfinished jobs....
===